# width and height of the maze
WIDTH		= 20
HEIGHT		= 15

# entry and exit point of the solver
ENTRY		= 19,14
EXIT		= 0,0

# The output file of the maze in format hexadecimal
OUTPUT_FILE	= maze.txt

# Set true if you want a perfect maze
PERFECT		= no

# give a value if you want a seed randomize map generator
SEED		= 42

Generator = auto
