# width and height of the maze
WIDTH=30
HEIGHT=20

# entry and exit point of the solver
ENTRY=0,0
EXIT=19,14

# The output file of the maze in format hexadecimal
OUTPUT_FILE=maze.txt

# Set true if you want a perfect maze
PERFECT=True

# give a value if you want a seed randomize map generator
SEED=None

TEDDY=MEVA
